name: Build & Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install 🔧
        run: yarn --ci

      - name: Build 👷‍♂️
        # Set BASENAME if the static page is hosted under a specific path segment (e.g. elastic.github.io/kibana-release-notes)
        # env:
        #   BASENAME: kibana-release-notes
        run: yarn build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
